// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProzorroDataMining.Infrastructure;

#nullable disable

namespace ProzorroDataMining.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829192232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentifierId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdentifierScheme")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("IdentifierScheme", "IdentifierId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.Tender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcuringEntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProzorroId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    b.HasIndex("ImportedAt");

                    b.HasIndex("ProcuringEntityName");

                    b.HasIndex("ProzorroId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("tenders", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.TenderContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("AwardId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DateSigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProzorroContractId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateSigned");

                    b.HasIndex("ProzorroContractId");

                    b.HasIndex("TenderId");

                    b.HasIndex("TenderId", "AwardId");

                    b.ToTable("tender_contracts", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.TenderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassificationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("TenderId");

                    b.HasIndex("ClassificationId", "TenderId");

                    b.ToTable("tender_items", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.TenderSupplier", b =>
                {
                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("");

                    b.HasKey("TenderId", "SupplierId", "AwardId");

                    b.HasIndex("AwardId");

                    b.HasIndex("SupplierId");

                    b.ToTable("tender_suppliers", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Infrastructure.Import.ImportSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackwardNextPageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ForwardNextPageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ForwardStartPageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("LastDirection")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LastPublicModified")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeedName")
                        .IsUnique();

                    b.ToTable("import_sync_states", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Infrastructure.Import.TenderImportJobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CandidatesFound")
                        .HasColumnType("integer");

                    b.Property<string>("ClassificationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("FeedItemsScanned")
                        .HasColumnType("integer");

                    b.Property<int?>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPages")
                        .HasColumnType("integer");

                    b.Property<string>("NextPageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("PageSize")
                        .HasColumnType("integer");

                    b.Property<string>("PrevPageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("ResultDirection")
                        .HasColumnType("integer");

                    b.Property<int?>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("tender_import_jobs", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Infrastructure.Import.TenderImportPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProzorroId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("PublicModified")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("SourceDateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAt");

                    b.HasIndex("ProzorroId");

                    b.HasIndex("PublicModified");

                    b.HasIndex("TenderId");

                    b.ToTable("tender_import_payloads", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.TenderContract", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tenders.Tender", "Tender")
                        .WithMany("Contracts")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.TenderItem", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tenders.Tender", "Tender")
                        .WithMany("Items")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.TenderSupplier", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tenders.Supplier", "Supplier")
                        .WithMany("Tenders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProzorroDataMining.Domain.Entities.Tenders.Tender", "Tender")
                        .WithMany("Suppliers")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Infrastructure.Import.TenderImportPayload", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tenders.Tender", "Tender")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.Supplier", b =>
                {
                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tenders.Tender", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Items");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
